// <auto-generated />
using System;
using AceSchoolPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AceSchoolPortal.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210725071514_Initial_DB")]
    partial class Initial_DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.ClassGrades", b =>
                {
                    b.Property<int>("class_grade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("class_grade_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("class_grade_id");

                    b.ToTable("ClassGrades");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.HouseGroups", b =>
                {
                    b.Property<int>("house_group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("house_group_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("house_group_id");

                    b.ToTable("HouseGroups");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Instructors", b =>
                {
                    b.Property<int>("instructor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassGradesclass_grade_id")
                        .HasColumnType("int");

                    b.Property<int?>("HouseGroupshouse_group_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("enrollment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("experience")
                        .HasColumnType("int");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("instructor_id");

                    b.HasIndex("ClassGradesclass_grade_id");

                    b.HasIndex("HouseGroupshouse_group_id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Students", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassGradesclass_grade_id")
                        .HasColumnType("int");

                    b.Property<int?>("HouseGroupshouse_group_id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("enrollment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.HasIndex("ClassGradesclass_grade_id");

                    b.HasIndex("HouseGroupshouse_group_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Subjects", b =>
                {
                    b.Property<int>("subject_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassGradesclass_grade_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subject_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subject_id");

                    b.HasIndex("ClassGradesclass_grade_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Instructors", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.ClassGrades", null)
                        .WithMany("instructors")
                        .HasForeignKey("ClassGradesclass_grade_id");

                    b.HasOne("AceSchoolPortal.Data.Entities.HouseGroups", null)
                        .WithMany("instructors")
                        .HasForeignKey("HouseGroupshouse_group_id");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Students", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.ClassGrades", null)
                        .WithMany("students")
                        .HasForeignKey("ClassGradesclass_grade_id");

                    b.HasOne("AceSchoolPortal.Data.Entities.HouseGroups", null)
                        .WithMany("students")
                        .HasForeignKey("HouseGroupshouse_group_id");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Subjects", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.ClassGrades", null)
                        .WithMany("subjects")
                        .HasForeignKey("ClassGradesclass_grade_id");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.ClassGrades", b =>
                {
                    b.Navigation("instructors");

                    b.Navigation("students");

                    b.Navigation("subjects");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.HouseGroups", b =>
                {
                    b.Navigation("instructors");

                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
