// <auto-generated />
using System;
using AceSchoolPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AceSchoolPortal.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210725121317_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.ClassGrades", b =>
                {
                    b.Property<int>("class_grade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Instructorsinstructor_id")
                        .HasColumnType("int");

                    b.Property<int?>("Studentsstudent_id")
                        .HasColumnType("int");

                    b.Property<int?>("Subjectssubject_id")
                        .HasColumnType("int");

                    b.Property<string>("class_grade_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("class_grade_id");

                    b.HasIndex("Instructorsinstructor_id");

                    b.HasIndex("Studentsstudent_id");

                    b.HasIndex("Subjectssubject_id");

                    b.ToTable("ClassGrades");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.HouseGroups", b =>
                {
                    b.Property<int>("house_group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Instructorsinstructor_id")
                        .HasColumnType("int");

                    b.Property<int?>("Studentsstudent_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("house_group_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("house_group_id");

                    b.HasIndex("Instructorsinstructor_id");

                    b.HasIndex("Studentsstudent_id");

                    b.ToTable("HouseGroups");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Instructors", b =>
                {
                    b.Property<int>("instructor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("enrollment_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("experience")
                        .HasColumnType("int");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("instructor_id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Students", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("enrollment_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Subjects", b =>
                {
                    b.Property<int>("subject_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Studentsstudent_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("subject_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subject_id");

                    b.HasIndex("Studentsstudent_id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.ClassGrades", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.Instructors", "Instructors")
                        .WithMany("ClassGrades")
                        .HasForeignKey("Instructorsinstructor_id");

                    b.HasOne("AceSchoolPortal.Data.Entities.Students", "Students")
                        .WithMany("ClassGrades")
                        .HasForeignKey("Studentsstudent_id");

                    b.HasOne("AceSchoolPortal.Data.Entities.Subjects", "Subjects")
                        .WithMany("ClassGrades")
                        .HasForeignKey("Subjectssubject_id");

                    b.Navigation("Instructors");

                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.HouseGroups", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.Instructors", "Instructors")
                        .WithMany()
                        .HasForeignKey("Instructorsinstructor_id");

                    b.HasOne("AceSchoolPortal.Data.Entities.Students", "Students")
                        .WithMany("HouseGroups")
                        .HasForeignKey("Studentsstudent_id");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Subjects", b =>
                {
                    b.HasOne("AceSchoolPortal.Data.Entities.Students", null)
                        .WithMany("Subjects")
                        .HasForeignKey("Studentsstudent_id");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Instructors", b =>
                {
                    b.Navigation("ClassGrades");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Students", b =>
                {
                    b.Navigation("ClassGrades");

                    b.Navigation("HouseGroups");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("AceSchoolPortal.Data.Entities.Subjects", b =>
                {
                    b.Navigation("ClassGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
